spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ebookstorage?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      #最大文件大小和单次最大请求大小,开始上传下载
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true
#  jackson:
#    time-zone: GMT+8
#    date-format: yyyy-MM-dd HH:mm:ss
#    default-property-inclusion: always
##    mode:  HTML5
#    encoding: UTF-8


mybatis:
  mapper-locations: classpath:mapper/*.xml
  #起别名
  type-aliases-package: com.example.entity
#日志
logging:
  level:
    root: info
    com.example: debug

# 分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql